apiVersion: v1
kind: Service

metadata:
  name: spring-petclinic-service
  namespace: petclinic

spec:
  selector:
    app: spring-petclinic-1

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

  type: NodePort

